Repository SquidDev-CC/plethora, pull requests merged in 2019-04, with the labels that each got.

#192 Chicken-related Mod Support
  build.gradle
  src/main/java/org/squiddev/plethora/api/method/ContextHelpers.java
  src/main/java/org/squiddev/plethora/api/method/wrapper/PlethoraMethod.java
  src/main/java/org/squiddev/plethora/integration/chickens/IntegrationChickens.java
  src/main/java/org/squiddev/plethora/integration/chickens/MetaChickens.java
  src/main/java/org/squiddev/plethora/integration/chickens/MethodsAnalyzer.java
  src/main/java/org/squiddev/plethora/integration/hatchery/IntegrationHatchery.java
  src/main/java/org/squiddev/plethora/integration/roost/IntegrationRoost.java
  src/main/java/org/squiddev/plethora/integration/roost/MethodsRoost.java
  src/main/java/org/squiddev/plethora/integration/vanilla/meta/MetaEntityLiving.java
Labels: enhancement

#194 Require CC:Tweaked to run, drop vanilla CC support
  ReadMe.md
  build.gradle
  gradle.properties
  src/main/java/org/squiddev/plethora/api/method/IResultExecutor.java
  src/main/java/org/squiddev/plethora/core/MethodWrapper.java
  src/main/java/org/squiddev/plethora/core/PeripheralProvider.java
  src/main/java/org/squiddev/plethora/core/PlethoraCore.java
  src/main/java/org/squiddev/plethora/core/PocketUpgradeModule.java
  src/main/java/org/squiddev/plethora/core/TurtleUpgradeModule.java
  src/main/java/org/squiddev/plethora/core/capabilities/DefaultCostHandler.java
  src/main/java/org/squiddev/plethora/core/executor/BasicExecutor.java
  src/main/java/org/squiddev/plethora/core/executor/ComputerAccessExecutor.java
  src/main/java/org/squiddev/plethora/core/executor/FutureTask.java
  src/main/java/org/squiddev/plethora/core/executor/NeverExecutor.java
  src/main/java/org/squiddev/plethora/core/executor/Task.java
  src/main/java/org/squiddev/plethora/core/executor/TaskRunner.java
  src/main/java/org/squiddev/plethora/gameplay/Plethora.java
  src/main/java/org/squiddev/plethora/gameplay/client/gui/GuiKeyboard.java
  src/main/java/org/squiddev/plethora/gameplay/client/gui/GuiMinecartComputer.java
  src/main/java/org/squiddev/plethora/gameplay/client/gui/GuiNeuralInterface.java
  src/main/java/org/squiddev/plethora/gameplay/minecart/CommandAPI.java
  src/main/java/org/squiddev/plethora/gameplay/minecart/EntityMinecartComputer.java
  src/main/java/org/squiddev/plethora/gameplay/redstone/BlockRedstoneIntegrator.java
  src/main/java/org/squiddev/plethora/gameplay/redstone/TileRedstoneIntegrator.java
  src/main/java/org/squiddev/plethora/gameplay/registry/Registration.java
  src/main/java/org/squiddev/plethora/integration/computercraft/ConverterTargetedPeripheral.java
  src/main/java/org/squiddev/plethora/integration/computercraft/MetaItemMedia.java
  src/main/java/org/squiddev/plethora/integration/computercraft/MetaItemPocketComputer.java
  src/main/java/org/squiddev/plethora/integration/computercraft/MetaItemTurtle.java
  src/main/java/org/squiddev/plethora/integration/computercraft/SpeakerPeripheralBase.java
  src/main/java/org/squiddev/plethora/integration/computercraft/TransferComputerAccess.java
  src/main/java/org/squiddev/plethora/integration/computercraft/WirelessModemPeripheralBase.java
  src/main/java/org/squiddev/plethora/integration/jei/UseInRecipeWrapper.java
  src/main/java/org/squiddev/plethora/utils/Helpers.java
  src/main/java/org/squiddev/plethora/utils/PlethoraTimings.java
Labels: enhancement, feedback wanted

#205 Astral Sorcery Support
  build.gradle
  src/main/java/org/squiddev/plethora/api/method/LuaList.java
  src/main/java/org/squiddev/plethora/integration/astralsorcery/IntegrationAstralSorcery.java
  src/main/java/org/squiddev/plethora/integration/astralsorcery/MetaBlocks.java
  src/main/java/org/squiddev/plethora/integration/astralsorcery/MetaItems.java
  src/main/java/org/squiddev/plethora/integration/astralsorcery/MethodsAstralSorcery.java
Labels: enhancement

#210 Lines in 3D canvasses
  src/main/java/org/squiddev/plethora/gameplay/modules/glasses/methods/MethodsCanvas3D.java
  src/main/java/org/squiddev/plethora/gameplay/modules/glasses/objects/ObjectRegistry.java
  src/main/java/org/squiddev/plethora/gameplay/modules/glasses/objects/object3d/Line3D.java
  src/main/java/org/squiddev/plethora/gameplay/modules/glasses/objects/object3d/MultiPoint3D.java
Labels: enhancement

#209 Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/mod_integration.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement, meta
